### ISSUE TITLE
En el readme, el enlace a la página debería estar escrito correctamente [texto a mostrar](link)

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-mateopappa#2]

**Comment by edme88** [comment]
El link de la página del readme no funciona.
El link debería ser:
`[Click aquí](https://ucc-labcompu2.github.io/proyecto2023-mateopappa/index.html)`

**Comment by mateopappa** [comment]
puse ese link. espero funcione
