### ISSUE TITLE
Si se selecciona el radio button de simular, y se clickea el boton de simular, los inputs se completan con NaN

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-mateopappa#5]
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-mateopappa/assets/8345007/5c3d497f-19ec-4273-aa5c-8a07e774de0d)
El funcionamiento no es correcto. Si el usuario selecciona el radio button de simular, y se clickea el boton de simular, los inputs no se deben completar si faltan valores para realizar el cálculo.

**Comment by mateopappa** [comment]
ok
